### ISSUE TITLE
Smartypants conflict

### ISSUE THREAD

**Issue by BenParizek** [jamiepittock/craft-typogrify#4]
Recently I installed Typogrify alongside another plugin using SmartyPants and everything stopped working.

I was able to resolve the issue by moving the libraries being [loaded in the Twig extension](https://github.com/jamiepittock/craft-typogrify/blob/master/typogrify/twigextensions/TypogrifyTwigExtension.php) to the primary plugin class file.

```
public function init()
{
  Craft::import('plugins.typogrify.lib.smartypants');
  Craft::import('plugins.typogrify.lib.php-typogrify');
}
```

**Comment by jamiepittock** [comment]
Fixed (finally) #5
