### ISSUE TITLE
Craft 3 port?

### ISSUE THREAD

**Issue by khalwat** [jamiepittock/craft-typogrify#7]
Are you planning to port this plugin to Craft 3? If not, I'd be happy to do it.

**Comment by jamiepittock** [comment]
Yeah I've been meaning to for a while. I'll sort it today.

**Comment by khalwat** [comment]
I was going to look into using this more modern PHP lib to do it:

https://github.com/adamaveray/PHPTypography

**Comment by khalwat** [comment]
Ported it:

https://github.com/nystudio107/craft3-typogrify

(needed it for a project)
